### ISSUE TITLE
Hardcoding cluster resources names prevents new service creation in the same namespace

### ISSUE THREAD

**Issue by rthallisey** [fusor/ansible-playbook-bundle#142]
```yaml
- name: set development deployment config state to {{ state }}
  openshift_v1_deployment_config:
    name: postgresql
    namespace: '{{ namespace }}'
    labels:
      app: rhscl-postgresql-apb
      service: postgresql
...
````
The deployment config name is hardcoded to ```postgresql```.  If I run a second postgresql apb in the same namespace then nothing will happen because the resources will already exist. This is the case for all our apbs.
