### ISSUE TITLE
support license field in abp.yaml file

### ISSUE THREAD

**Issue by matzew** [fusor/ansible-playbook-bundle#154]
It would be nice if the `apb.yaml` would support (and being valid) a `license:` field, so that one could do:

```yaml
version: 1.0
license: Apache 2.0
name: my-cool-apb
...
```
