### ISSUE TITLE
Multi-line strings in apb.yml get corrupted during prepare

### ISSUE THREAD

**Issue by aweiteka** [fusor/ansible-playbook-bundle#84]
When the apb.yml spec file has a multi-line string, e.g....

```yaml
metadata:
  documentationUrl: https://access.redhat.com
  imageUrl: ansibleplaybookbundle/mongodb-apb
  dependencies: []
  displayName: MongoDB-Persistent (APB)
  longDescription: |-
    This template provides a standalone MongoDB server with a database
    created. The database is stored on persistent storage.  The database
    name, username, and password are chosen via parameters when provisioning
    this service.
```

...running apb prepare corrupts the file so it's no longer valid yaml, e.g.

```yaml
metadata:
  documentationUrl: https://access.redhat.com
  imageUrl: ansibleplaybookbundle/mongodb-apb
  dependencies: []
  displayName: MongoDB-Persistent (APB)
  longDescription: This template provides a standalone MongoDB server with a database
created. The database is stored on persistent storage.  The database
name, username, and password are chosen via parameters when provisioning
this service.
```

It's unexpected to have the apb.yml file change when running prepare. I made edits to it that are intentional. I understand this can be disabled with --skip-spec-update opt but why do we do it?
